# Shout Out to SOFe\Capital for their workflow file.
name: CI
on:
  - push
  - pull_request
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.0"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}
      - name: Clone Swift-Strider/DiamondDatas
        uses: GuillaumeFalourd/clone-github-repo-action@v1
        with:
          owner: 'Swift-Strider'
          repository: 'DiamondDatas'
      - name: phpstan analyze
        run: |
          composer install --ignore-platform-reqs
          composer run -- phpstan -c .github/ci.phpstan.neon
  style-check:
    name: Style Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.0"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}
      - run: |
          composer install --ignore-platform-reqs
          composer run -- fmt --dry-run --diff
